const data= [
      {
        id: 0,
        title: 'Multi-Post Stories',
        image: 'assest/placeholder.png',
        big_image: 'assest/Big.png',
        overview: 'A daily selection of privately personalized reads; no accounts or sign-ups required. has been the industry'+"'"+'s standard dummy text ever since the 1500s, when an unknown printer took a standard dummy text.',
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry'+"'"+'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it 1960s with the releaLorem Ipsum is simply dummy text of the printing and typesetting  ever since the 1500s, when an unknown printer took a galley of type veris lapoa todoe.',
        tags:'Css,Html,Bootstrap,Ruby',
        live:'#',
        repo:'#',
        alt:'placeholder',
        big_alt:'Big_Placeholder',
      },
      {
        id: 1,
        title: 'Multi-Post Stories',
        image: 'assest/placeholder.png',
        big_image: 'assest/Big.png',
        overview: 'A daily selection of privately personalized reads; no accounts or sign-ups required. has been the industry'+"'"+'s standard dummy text ever since the 1500s, when an unknown printer took a standard dummy text.',
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry'+"'"+'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it 1960s with the releaLorem Ipsum is simply dummy text of the printing and typesetting  ever since the 1500s, when an unknown printer took a galley of type veris lapoa todoe.',
        tags:'Css,Html,Bootstrap,Ruby',
        live:'#',
        repo:'#',
        alt:'placeholder',
        big_alt:'Big_Placeholder',
      },
      {
        id: 2,
        title: 'Multi-Post Stories',
        image: 'assest/placeholder.png',
        big_image: 'assest/Big.png',
        overview: 'A daily selection of privately personalized reads; no accounts or sign-ups required. has been the industry'+"'"+'s standard dummy text ever since the 1500s, when an unknown printer took a standard dummy text.',
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry'+"'"+'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it 1960s with the releaLorem Ipsum is simply dummy text of the printing and typesetting  ever since the 1500s, when an unknown printer took a galley of type veris lapoa todoe.',
        tags:'Css,Html,Bootstrap,Ruby',
        live:'#',
        repo:'#',
        alt:'placeholder',
        big_alt:'Big_Placeholder',
      },
      {
        id: 3,
        title: 'Multi-Post Stories',
        image: 'assest/placeholder.png',
        big_image: 'assest/Big.png',
        overview: 'A daily selection of privately personalized reads; no accounts or sign-ups required. has been the industry'+"'"+'s standard dummy text ever since the 1500s, when an unknown printer took a standard dummy text.',
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry'+"'"+'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it 1960s with the releaLorem Ipsum is simply dummy text of the printing and typesetting  ever since the 1500s, when an unknown printer took a galley of type veris lapoa todoe.',
        tags:'Css,Html,Bootstrap,Ruby',
        live:'#',
        repo:'#',
        alt:'placeholder',
        big_alt:'Big_Placeholder',
      }
    ]
export default data;